### ISSUE TITLE
Campo "Data Venda

### ISSUE THREAD

**Issue by lucasdanielian** [arlenmendes/stock-control#3]
**Procedimento:**

Cadastrar novo produto

**Erro:**

Na tabela de listagem das vendas, não está sendo preenchido o campo "Data Venda", que deve mostrar a data inserida no cadastro (problema ilustrado na imagem abaixo).

![erro](https://user-images.githubusercontent.com/26883866/35733271-e669a506-0803-11e8-80dc-4b8685488628.jpeg)

**Comment by arlenmendes** [comment]
Corrigido no commit 9969cc67450dadc8b804ec58325676b66ae0a87d.
